columnSuffix: null
contentColumnType: string
fieldGroup: d4401c02-0ab2-48b2-8f90-b3fba660540d # Gallery
handle: category
instructions: null
name: Category
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:f242565a-a345-41ba-a754-21e6101195d9' # Type
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
