columnSuffix: vwcyghuk
contentColumnType: boolean
fieldGroup: d4401c02-0ab2-48b2-8f90-b3fba660540d # Gallery
handle: featured
instructions: 'Featured on front page.'
name: Featured
searchable: false
settings:
  default: false
  offLabel: 'No'
  onLabel: 'Yes'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
