columnSuffix: xtgosggv
contentColumnType: text
fieldGroup: 6b0c7eb4-cf99-49b5-ae30-d9c6bff0f3d1 # Optimized Images
handle: galleryItem
instructions: null
name: 'Gallery Item'
searchable: false
settings:
  displayDominantColorPalette: true
  displayLazyLoadPlaceholderImages: false
  displayOptimizedImageVariants: true
  fieldVolumeSettings:
    __assoc__:
      -
        - galleryEntry
        - '*'
  variants:
    -
      __assoc__:
        -
          - width
          - '1200'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - ''
    -
      __assoc__:
        -
          - width
          - '576'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
