columnSuffix: hakfmmpi
contentColumnType: string(16)
fieldGroup: d4401c02-0ab2-48b2-8f90-b3fba660540d # Gallery
handle: year
instructions: null
name: Year
searchable: false
settings:
  byteLimit: null
  charLimit: 4
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
