dateModified: 1789514243
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: sections
      type: heading
    -
      defaultSort:
        - structure
        - asc
      disabled: false
      key: 'section:0727a1ba-2e97-401b-acf0-62404bd96183' # Gallery Item
      tableAttributes:
        - postDate
        - 'field:1aebd8e7-251a-4e04-be61-f87dfde4e0ce' # Category
        - 'field:7cfcd554-f789-4144-a909-d1df4ba3ba6f' # Price
        - 'field:ffe73972-cec1-4371-b0b1-db43732696b6'
        - 'field:0fec8553-9509-41e1-a7fb-e4dc3ade19ce' # Photo
        - link
      type: native
    -
      key: 'section:58ff4b34-297a-4bc5-8578-808b82346497' # News
      type: native
    -
      heading: 'BY TYPE'
      type: heading
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\fields\conditions\RelationalFieldConditionRule
            elementId: '817'
            fieldUid: 1aebd8e7-251a-4e04-be61-f87dfde4e0ce # Category
            operator: relatedTo
            uid: c08a9e0b-fb53-4148-944a-b87e75f85fb1
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:597d3071-582f-49d4-974e-f73e79724bb3'
      label: 'Shack Plaques'
      tableAttributes:
        - link
        - 'field:0fec8553-9509-41e1-a7fb-e4dc3ade19ce' # Photo
        - 'field:ffe73972-cec1-4371-b0b1-db43732696b6'
      type: custom
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\fields\conditions\RelationalFieldConditionRule
            elementId: '55'
            fieldUid: 1aebd8e7-251a-4e04-be61-f87dfde4e0ce # Category
            operator: relatedTo
            uid: f11f49b7-7660-40c8-acb6-12a07aaf170a
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:0698acbd-ee34-4c18-8cbd-ad2c7401aa6e'
      label: 'Barbie Bulbs'
      tableAttributes:
        - link
        - 'field:0fec8553-9509-41e1-a7fb-e4dc3ade19ce' # Photo
        - 'field:ffe73972-cec1-4371-b0b1-db43732696b6'
      type: custom
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\fields\conditions\RelationalFieldConditionRule
            elementId: '50'
            fieldUid: 1aebd8e7-251a-4e04-be61-f87dfde4e0ce # Category
            operator: relatedTo
            uid: 06c7aaf1-82f6-451e-ba86-f32e89cb7b29
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:eeaae75d-5633-41e2-9e73-e688580f9b08'
      label: Embroidery
      tableAttributes:
        - section
        - 'field:ffe73972-cec1-4371-b0b1-db43732696b6'
        - 'field:0fec8553-9509-41e1-a7fb-e4dc3ade19ce' # Photo
        - postDate
      type: custom
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\fields\conditions\RelationalFieldConditionRule
            elementId: '53'
            fieldUid: 1aebd8e7-251a-4e04-be61-f87dfde4e0ce # Category
            operator: relatedTo
            uid: 9ea29851-d02d-4aeb-a749-cbea5bc3e5ff
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:8c89dad1-9578-447c-ac14-e6c6fe7faee9'
      label: Collage/Multimedia
      tableAttributes:
        - link
        - 'field:0fec8553-9509-41e1-a7fb-e4dc3ade19ce' # Photo
        - 'field:ffe73972-cec1-4371-b0b1-db43732696b6'
      type: custom
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\fields\conditions\RelationalFieldConditionRule
            elementId: '51'
            fieldUid: 1aebd8e7-251a-4e04-be61-f87dfde4e0ce # Category
            operator: relatedTo
            uid: c6ca7c8b-1e2c-45e7-beb8-a34bce8d09a4
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:97976a11-5a33-4f77-b33a-3a18575b57a2'
      label: Paintings
      tableAttributes:
        - link
        - 'field:ffe73972-cec1-4371-b0b1-db43732696b6'
        - 'field:0fec8553-9509-41e1-a7fb-e4dc3ade19ce' # Photo
      type: custom
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\fields\conditions\RelationalFieldConditionRule
            elementId: '52'
            fieldUid: 1aebd8e7-251a-4e04-be61-f87dfde4e0ce # Category
            operator: relatedTo
            uid: c8a3235a-2929-4d69-b9db-c9a11010a681
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:80854a67-1598-4084-b756-36d4963bb5f6'
      label: 'Pen and Ink'
      tableAttributes:
        - link
        - 'field:ffe73972-cec1-4371-b0b1-db43732696b6'
        - 'field:0fec8553-9509-41e1-a7fb-e4dc3ade19ce' # Photo
      type: custom
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\fields\conditions\RelationalFieldConditionRule
            elementId: '54'
            fieldUid: 1aebd8e7-251a-4e04-be61-f87dfde4e0ce # Category
            operator: relatedTo
            uid: a852639a-aebe-40ac-a2ed-ce489cf055c3
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:05a26d4b-326a-45ec-bbc6-040f942dc4cd'
      label: Sculpture
      tableAttributes:
        - link
        - 'field:ffe73972-cec1-4371-b0b1-db43732696b6'
        - 'field:0fec8553-9509-41e1-a7fb-e4dc3ade19ce' # Photo
      type: custom
    -
      heading: Pages
      type: heading
    -
      key: 'single:b023c856-388e-49d5-b3c3-af0860a15198' # About
      type: native
    -
      key: 'single:18072655-b712-4cc9-adec-60d41d875047' # Gallery Index
      type: native
    -
      key: 'single:88155c54-8fb6-4514-bb54-4f3aa3bf9dae' # News Index
      type: native
    -
      key: 'single:45459bd9-67ba-4bc9-a2de-f44f827f1820' # Privacy  Policy
      type: native
    -
      key: 'single:64861cfc-b63e-44c1-94d3-89b36e800555' # Contact Celeste
      type: native
    -
      heading: ''
      type: heading
    -
      key: 'single:d242db6c-df95-4f02-8154-9e7770288fd9' # Index2
      type: native
email:
  fromEmail: fultonchain@gmail.com
  fromName: 'Celeste Hanlon'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  assets:
    hasUrls: true
    name: Assets
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: '@web/assets'
  photos:
    hasUrls: true
    name: Photos
    settings:
      path: '@webroot/photos'
    type: craft\fs\Local
    url: '@web/photos'
meta:
  __names__:
    0a804e5e-1a24-497d-a7bf-9731f78112d8: 'Gallery Item' # Gallery Item
    0fec8553-9509-41e1-a7fb-e4dc3ade19ce: Photo # Photo
    1aebd8e7-251a-4e04-be61-f87dfde4e0ce: Category # Category
    1dadf828-8f91-43ae-afa5-d49f8fe7f5cb: 'Category Image' # Category Image
    3f17efca-0866-4cd0-86b8-44266b431997: 'Gallery Index' # Gallery Index
    4e6389c3-4894-45bd-a376-30165826e3b5: 'News Index' # News Index
    6b0c7eb4-cf99-49b5-ae30-d9c6bff0f3d1: 'Optimized Images' # Optimized Images
    6cf9b141-6dd5-44b3-9788-59a8155cd854: Bio # Bio
    7cfcd554-f789-4144-a909-d1df4ba3ba6f: Price # Price
    7f94d647-d301-487a-8546-fc72a82bb31b: About # About
    8d772998-c88e-4484-aa9a-1e2691c8c3a9: 'Gallery Item' # Gallery Item
    09a42df4-9b5b-47bf-8d1e-57fe2fea68a0: 'Public Schema' # Public Schema
    9b09e355-8da4-4607-a6a9-cefedf852ff3: 'Public Schema' # Public Schema
    15ddaabb-0b3b-4e37-87f7-afd53a992ae5: 'Celeste Hanlon' # Celeste Hanlon
    028f0e28-62ee-4616-873e-a826084cea8e: 'Gallery Thumbnail' # Gallery Thumbnail
    47aba095-5b23-4730-8fe9-c42639cbb8c6: Default # Default
    58ff4b34-297a-4bc5-8578-808b82346497: News # News
    83eb1363-c131-402c-a350-114f719f978d: Common # Common
    0727a1ba-2e97-401b-acf0-62404bd96183: 'Gallery Item' # Gallery Item
    861fbacf-15bb-444c-a03e-ffe4c9b625a8: Default # Default
    3988dbe6-9f79-448e-bad4-87e38fa9c092: 'Plain Text' # Plain Text
    8263b1df-8efc-4dbf-84b4-347808ba8d11: Assets # Assets
    8279de5a-806c-46c6-9f9e-6978aa49fa3f: 'Public Schema' # Public Schema
    9661edd6-abcd-40f5-8297-18c412471129: 'Privacy  Policy' # Privacy  Policy
    45459bd9-67ba-4bc9-a2de-f44f827f1820: 'Privacy  Policy' # Privacy  Policy
    45897eaa-bc55-4a29-a6b4-dfbd59714945: Year # Year
    59589df6-ee58-471a-b688-418c40448ebb: 'Link Text' # Link Text
    64861cfc-b63e-44c1-94d3-89b36e800555: 'Contact Celeste' # Contact Celeste
    88155c54-8fb6-4514-bb54-4f3aa3bf9dae: 'News Index' # News Index
    399753ed-5701-499c-adce-27b6c9e7e329: 'Public Schema' # Public Schema
    18072655-b712-4cc9-adec-60d41d875047: 'Gallery Index' # Gallery Index
    44083637-0c63-4f56-a344-9c83304136f4: 'Slider Image' # Slider Image
    68041276-7b3d-498b-9a92-f36db2dfe659: 'Celeste Hanlon' # Celeste Hanlon
    a5940ace-7123-46e0-9a70-cc841f70f3ff: 'Contact Celeste' # Contact Celeste
    af59a311-51e7-4dc9-9937-a4294b214ad1: 'Front Page' # Front Page
    b023c856-388e-49d5-b3c3-af0860a15198: About # About
    b1bfef9e-b5d9-4697-a3b0-c699055ac415: Category # Category
    b9843c1c-1c9e-49e5-8a40-9592d9270aee: 'Banner Link' # Banner Link
    c2d83085-2e41-4597-8114-f21defb03ef2: '500 Wide' # 500 Wide
    c4ed2e4f-9765-4ecf-a0d9-8a1c8dc9f086: Index2 # Index2
    c9ee7a04-e141-4e15-97a1-4021f547902f: 'Public Schema' # Public Schema
    c154a5e8-8976-4775-88e3-d5bc32ed83b6: 'Public Schema' # Public Schema
    cb6b6826-6262-4cd3-a1a9-3142974ff8a7: Simple # Simple
    d3cbd93b-73a8-4b2a-8fdf-0881e71e7215: Size # Size
    d242db6c-df95-4f02-8154-9e7770288fd9: Index2 # Index2
    d4401c02-0ab2-48b2-8f90-b3fba660540d: Gallery # Gallery
    d8287e76-204a-4eef-bf11-a78b04a597d1: 'Public Schema' # Public Schema
    e37f5a9b-c599-46f5-89e3-7a681189f376: Medium # Medium
    e8716a57-f632-4b58-8c90-fa5412e61e3b: 'Slider Image' # Slider Image
    f70b07fc-6eb3-4b53-8e0c-31818172636d: 'Public Schema' # Public Schema
    f242565a-a345-41ba-a754-21e6101195d9: Type # Type
    ff5d000b-7f43-46bc-95c6-1eb882983681: 'Banner Text' # Banner Text
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: "ul#alerts li{\r\n    display: none !important;\r\n}"
      cacheBusting: true
      cssFile: ''
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: BCO1V64T3BVRC112AMOLZSA3
    schemaVersion: 1.0.0
    settings:
      allowUpScaledImageVariants: true
      assetVolumeSubFolders: false
      autoSharpenScaledImages: true
      capSilhouetteSvgSize: true
      createColorPalette: false
      createPlaceholderSilhouettes: false
      imageTransformTypeSettings:
        __assoc__:
          -
            - nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform
            -
              __assoc__:
                -
                  - domain
                  - ''
                -
                  - apiKey
                  - ''
                -
                  - securityToken
                  - ''
                -
                  - unsharpMask
                  - '20'
          -
            - nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
          -
            - nystudio107\imageoptimizethumbor\imagetransforms\ThumborImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
                -
                  - securityKey
                  - ''
      lowerQualityRetinaImageVariants: true
      sharpenScaledImagePercentage: 50
      transformClass: nystudio107\imageoptimize\imagetransforms\CraftImageTransform
  quick-filters:
    edition: standard
    enabled: false
    licenseKey: CUZP99B0BYG5KMQ84738VR5P
    schemaVersion: 1.0.0
  retcon:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: O8MYXJ75UCUI5TDSI64YJHGE
    schemaVersion: 3.0.13
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      excludeNonCanonicalUrls: false
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: true
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 0
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
      siteGroupsSeparate: true
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: true
      truncateTitleTags: true
  typogrify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Celeste Hanlon'
  retryDuration: null
  schemaVersion: 4.17.0.3
  timeZone: America/New_York
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
