defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  68041276-7b3d-498b-9a92-f36db2dfe659: # Celeste Hanlon
    enabledByDefault: true
    hasUrls: true
    template: _about.twig
    uriFormat: about
type: single
