defaultPlacement: end
enableVersioning: true
handle: news
name: News
propagationMethod: all
siteSettings:
  68041276-7b3d-498b-9a92-f36db2dfe659: # Celeste Hanlon
    enabledByDefault: true
    hasUrls: true
    template: news/_entry
    uriFormat: 'news/{slug}'
type: channel
