defaultPlacement: end
enableVersioning: true
handle: newsIndex
name: 'News Index'
propagationMethod: all
siteSettings:
  68041276-7b3d-498b-9a92-f36db2dfe659: # Celeste Hanlon
    enabledByDefault: true
    hasUrls: true
    template: news/index.twig
    uriFormat: news
type: single
